### ISSUE TITLE
module 'tfshearlab.tfsheardecrec' has no attribute 'tfshearrecadjoint2D'

### ISSUE THREAD

**Issue by linfengyu77** [arsenal9971/tfshearlab#1]
I installed tfshearlab acorrding to the command "pip install https://github.com/arsenal9971/tfshearlab/archive/master.zip", and julia 0.7.0 (windows 64bit) , Shearlab.jl (by running julia> Pkg.add("Shearlab")) and Pyjulia (by running pip install julia).
I also running the command julia> 'ENV["PYTHON"]="D:\\Anaconda3\\python.exe"; Pkg.add("PyCall"); Pkg.build("PyCall") to make the Julia and Python enviroment to coincide .  The errors occured when I import tfshearlab in python (3.7.3). 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\tfshearlab\__init__.py", line 8, in <module>
    from .tfsheardecrec import *
AttributeError: module 'tfshearlab.tfsheardecrec' has no attribute 'tfshearrecadjoint2D'

**Comment by harbarex** [comment]
Did you find a solution for this? I followed the same steps but am unable to import shearlab in an anaconda env
